version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  logstash:
    image: docker.elastic.co/logstash/logstash:5.5.3
    container_name: logstash
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /usr/local/logstash/config:/usr/share/logstash/config/
      - /usr/local/logstash/pipeline:/usr/share/logstash/pipeline/
    ports:
      - 5044:5044
      
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.3
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://172.16.23.55:9200"
      - "ELASTICSEARCH_USERNAME=elastic"
      - "ELASTICSEARCH_PASSWORD=changeme"
    ports:
      - "5601:5601"
    
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet: