version: '3'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:5.5.3
    container_name: logstash
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /usr/local/logstash/config:/usr/share/logstash/config/
      - /usr/local/logstash/pipeline:/usr/share/logstash/pipeline/
    ports:
      - 5044:5044
networks:
  default:
    external:
      name: elastic_esnet